# This workflow will install Python dependencies and run the algo_crossover.py script.
#
# IMPORTANT: GitHub Actions are NOT designed for infinitely looping processes.
# This workflow will run for a maximum of 6 hours (default for public repos)
# and then be terminated. For a truly continuous bot, consider a dedicated server,
# cloud platform, or Docker deployment.

name: Algo Crossover Runner # <--- Changed name to be unique!

on:
  push:
    branches: [ "main" ]
  # Allows you to manually trigger the workflow from the GitHub Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run_algo: # Renamed job to distinguish from previous bot=========================
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        # Install common libraries
        pip install pandas requests pytz ta
        pip install delta_rest_client # Assuming it's pip-installable.

    - name: Execute Algo Crossover Script
      run: |
        python algo_crossover.py # <--- Ensuring this runs the NEW script============================================

    # Optional: Add steps here for notifications on script completion/failure,
    # or to upload logs if the script exits.
