name: BTC GEX Chart Uploader

on:
  # Removed the 'schedule' trigger to prevent automatic runs.
  workflow_dispatch: # Allows manual triggering from GitHub Actions tab
    # You can add inputs here if you want to pass parameters when manually triggering
    # inputs:
    #   some_param:
    #     description: 'A parameter for manual runs'
    #     required: false
    #     default: 'default_value'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use a recent Python 3 version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests matplotlib boto3 pytz gspread oauth2client

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1 # <--- IMPORTANT: REPLACE THIS with your S3 bucket's region (if applicable)

    - name: Run Python script
      run: |
        python gex_monitor.py # <--- IMPORTANT: REPLACE THIS with the actual name of your Python script (e.g., gex_monitor.py or your new script's name)