# This workflow will install Python dependencies and run your trading bot script.
#
# IMPORTANT: GitHub Actions are NOT designed for infinitely looping processes.
# This workflow will run for a maximum of 6 hours (default for public repos)
# and then be terminated. For a truly continuous bot, consider a dedicated server,
# cloud platform, or Docker deployment.

name: Trading Bot Runner

on:
  push:
    branches: [ "main" ]
  # Allows you to manually trigger the workflow from the GitHub Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        # Install common libraries
        pip install pandas requests pytz ta
        # Install delta_rest_client. Assuming it's pip-installable.
        pip install delta_rest_client

        # If you have a requirements.txt file, you can use this instead:
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Execute Trading Bot Script
      # The 'env' block has been REMOVED because credentials are now hardcoded
      # directly in the trading_bot.py script as per your request.
      run: |
        python trading_bot.py

    # Optional: Add steps here for notifications on script completion/failure,
    # or to upload logs if the script exits.
